name: Build Pre-release

# --- for testing ---
on:
  push:
    branches:
      - 'feature/update-ci-workflows'
  workflow_dispatch:

jobs:
  build-library:
    name: Build NuGet Pre-release
    # This job runs if the PROJECT_TO_PACK repository variable is defined.
    if: vars.PROJECT_TO_PACK != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 } # Full history is required for MinVer

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.100-preview.7.25380.108
          dotnet-quality: preview
      # minver-cli must be registered as a local tool in .config/dotnet-tools.json
      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Get pre-release version
        id: version
        run: |
          # Run the new dnx command and pipe to tail to get only the last line (the version).
          VERSION=$(dnx minver-cli -y -p preview | tail -n 1)
          echo "Discovered version: $VERSION"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Run Tests
        run: dotnet run .build/targets.cs --target test

      - name: Pack NuGet Pre-release Package
        # The version from the previous step is passed to your build script.
        run: dotnet run .build/targets.cs --target pack --packProject ${{ vars.PROJECT_TO_PACK }} --version ${{ env.APP_VERSION }}

      - name: Upload NuGet Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-artifact-${{ env.APP_VERSION }}
          path: dist/nuget/


  build-application:
    name: Build App for ${{ matrix.os }}-${{ matrix.arch }}
    # This job runs if the PROJECT_TO_PUBLISH repository variable is defined.
    if: vars.PROJECT_TO_PUBLISH != ''
    runs-on: ${{ matrix.runner_os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { runner_os: windows-latest, os: win, arch: x64 }
          - { runner_os: ubuntu-latest, os: linux, arch: x64 }
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 } # Full history is required for MinVer

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Get pre-release version
        id: version
        run: |
          VERSION=$(dnx minver-cli -y -p preview | tail -n 1)
          echo "Discovered version: $VERSION"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Run Tests
        run: dotnet run .build/targets.cs --target test

      - name: Build and Publish Pre-release for ${{ matrix.os }}-${{ matrix.arch }}
        # The version is passed to the publish target in your build script.
        run: dotnet run .build/targets.cs --target publish --os ${{ matrix.os }} --arch ${{ matrix.arch }} --publishProject ${{ vars.PROJECT_TO_PUBLISH }} --version ${{ env.APP_VERSION }}

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact-${{ matrix.os }}-${{ matrix.arch }}-${{ env.APP_VERSION }}
          # The path is updated to match the C# script's output directory.
          path: dist/publish/